apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-cpu
data:
  fluent.conf: |
    # Fluentd configuration for CPU-intensive node group
    # Add configuration specific to CPU metrics and logs
